apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: app:nowawersja
          ports:
            - containerPort: 8080